[project]
name = "chefsupport-ai-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi~=0.111",
  "uvicorn~=0.30",
  "pydantic~=2.8",
  "httpx~=0.27",
]

[tool.uv]
system-site-packages = false
python = "3.11"
